version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"  # Expose backend on port 5000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    environment:
      - NEXT_PUBLIC_API_URL=http://10.12.7.7:5000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge