# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"  # Expose backend on port 3001
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000  # Backend URL within the same Docker network
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge