name: Build and Deploy with Docker

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Assuming you're using a self-hosted runner on your server
    steps:
      # Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for building multi-stage images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub if needed (Optional if pushing images to Docker Hub)
      # Uncomment the lines below if you're pushing to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and deploy containers using Docker Compose
      - name: Build and deploy containers
        run: |
          docker-compose down  # Stop and remove existing containers
          docker-compose up -d --build  # Build and start containers in detached mode
