name: Deploy to Ubuntu VM using Docker

on:
  push:
    branches:
      - main  # Adjust if necessary

jobs:
  deploy:
    runs-on: self-hosted  # Uses your local runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t your_dockerhub_username/backend:latest ./backend
          docker push your_dockerhub_username/backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t your_dockerhub_username/frontend:latest ./frontend
          docker push your_dockerhub_username/frontend:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
